var name = "Sundaram";
var reg_no = 12345;
var course = "Computer Science";
var marks = 95;
let r = "chanda";
let a = 18;
let y = 23;
let z = 23;
x = y + z;
console.log(name);
console.log(reg_no);
console.log(course);
console.log(marks);
console.log(x);
console.log(r);
console.log(a);
console.log(name + " is a student of " + course + " with registration number " + reg_no + " and scored " + marks + " marks.");
var isValid = true;
console.log("Is the data valid? " + isValid);
